### ISSUE TITLE
Allow camera to rotate behind floor

### ISSUE THREAD

**Issue by tigrouind** [ficsit-felix/ficsit-felix#85]
It could be useful to view what is below map / floor by rotating camera (eg : to see wrongly placed foundations that are below floor)
Actually the viewer automatically prevent this (on purpose).

**Comment by bitowl** [comment]
The 2D map that is currently placed should be way below everything that can be placed on the map.
In case there are still foundations placed below that, you should be able to disable the map in the settings to see them.

If you are refererring to the point that the camera rotates around: That can be changed by clicking on an object that lies further below and then clicking on "Focus", so that the camera is centered on that object.

Another solution might be to implement the Fly camera from the three.js examples.

**Comment by tigrouind** [comment]
Yes I was referring the way camera rotates around. It's limited to an half sphere.
The 2D map is not the problem. Most 3D objects (including foundations) are well above that map (as you explained).

I tried your suggestion, it helps, but it is cumbersome : I have to pick a object, move it to the right position (eg : to lower it and move it at center of where I want to rotate around). click on "Focus" and finally move camera.

See here : 
https://imgur.com/a/cEucr3q

First image is as low as I can get without using focus. My goal is to view the low foundations as in the red square. Second image is when using "Focus" after lowering some object.  Still, I cannot view a lot of the bottom part of the factory. It would be a piece of cake if not limited to an half sphere.

**Comment by bitowl** [comment]
I made a version on the develop branch (deployed at https://ficsit-felix-d092sr3ew.now.sh) that is not restricted to the upper hemisphere.
Panning inverted on the forward axis when you are on the lower hemisphere, though.
